// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
"use client";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  useEffect(() => {
    // Google Analytics script
    const script = document.createElement("script");
    script.src = "https://www.googletagmanager.com/gtag/js?id=G-H61J4LFWBB";
    script.async = true;
    document.head.appendChild(script);

    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());
    gtag("config", "G-H61J4LFWBB");
  }, []);

  return (
    <html lang="en">
      <Head>
        <title>
          {" "}
          FractIt - Tokenized Real Estate Investing | Earn Rental Yields
        </title>
        <meta
          name="description"
          content="Democratizing real estate investing. Fractit offers fractional ownership through FNFTs. Earn from rental yields and potential capital gains. Investing in real estate, simplified."
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}> {children}</body>
    </html>
  );
}
