// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
"use client";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   // Google Analytics script
  //   const script = document.createElement("script");
  //   script.src = "https://www.googletagmanager.com/gtag/js?id=G-H61J4LFWBB";
  //   script.async = true;
  //   document.head.appendChild(script);

  //   window.dataLayer = window.dataLayer || [];
  //   function gtag() {
  //     dataLayer.push(arguments);
  //   }
  //   gtag("js", new Date());
  //   gtag("config", "G-H61J4LFWBB");
  // }, []);
  useEffect(() => {
    // Check if script already exists before adding it
    if (
      !document.querySelector(
        'script[src="https://www.googletagmanager.com/gtag/js?id=G-H61J4LFWBB"]'
      )
    ) {
      const script = document.createElement("script");
      script.src = "https://www.googletagmanager.com/gtag/js?id=G-H61J4LFWBB";
      script.async = true;
      document.head.appendChild(script);

      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());
      gtag("config", "G-H61J4LFWBB");
    }
  }, []);

  return (
    <html lang="en">
      <head>
        <title>
          FractIt - Tokenized Real Estate Investing | Earn Rental Yields
        </title>
        <meta
          name="description"
          content="Democratizing real estate investing. Fractit offers fractional ownership through FNFTs. Earn from rental yields and potential capital gains. Investing in real estate, simplified."
        />
        <meta
          property="og:image"
          content="https://drive.google.com/file/d/1RTuQxWYmu4WLagmeLR4P3TeHAIDpKfsg/view?usp=sharing"
        />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}> {children}</body>
    </html>
  );
}
